const DEFAULT_ERROR = 500;
const NOT_FOUND = 404;
const INCORRECT_DATA = 400;
const CREATED_CODE = 201;
const DEFAULT_OK_CODE = 200;

module.exports = {
  DEFAULT_ERROR,
  NOT_FOUND,
  INCORRECT_DATA,
  CREATED_CODE,
  DEFAULT_OK_CODE,
};
